\documentclass{beamer}\usepackage[]{graphicx}\usepackage[]{color}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{1, 0.894, 0.769}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.824,0.412,0.118}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{1,0.894,0.71}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.824,0.706,0.549}{#1}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{1,0.894,0.769}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{1,0.894,0.769}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.941,0.902,0.549}{#1}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.804,0.776,0.451}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.78,0.941,0.545}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{1,0.78,0.769}{#1}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage{../371g-slides}
\title{Simulation 1}
\subtitle{Lecture 22}
\author{STA 371G}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}
  
  

  \frame{\maketitle}

  % Show outline at beginning of each section
  \AtBeginSection[]{
    \begin{frame}<beamer>
      \tableofcontents[currentsection]
    \end{frame}
  }

  %%%%%%% Slides start here %%%%%%%

  \begin{darkframes}
    \begin{frame}{What is simulation?}
      \begin{itemize}[<+->]
        \item When we have data, we can use regression models to predict an outcome based on input data that we know we will have available.
        \item However, sometimes we don't have the data we need to build a model, or we might want to understand the full range of possible outcomes rather than predicting a single outcome.
      \end{itemize}
    \end{frame}

    \begin{frame}{Examples of simulation}
      \begin{itemize}
        \item What will the value of my retirement portfolio look like in 30 years, and how does that depend on market conditions over that time span?
        \item What profit should I expect to see from a business selling team hats during the NBA playoffs, and how does that vary depending on who wins the playoffs and what kinds of hats I order?
        \item What sorts of returns are possible if I decide to drill for oil in a newly-discovered field, and how does that depend on my assumptions about drilling costs and the likelihood of success?
      \end{itemize}
    \end{frame}

    \begin{frame}{Simulation framework}
      \begin{enumerate}
        \item Define an quantity of interest that represents the outcome.
        \item Articulate a set of assumptions about the problem.
        \item Simulate the random processes that are inherent in determining the outcome.
        \item Compute the quantity of interest.
        \item Repeat steps 3-4 a large number of times, and examine the long-term distribution of the quantity.
      \end{enumerate}

      \pause

      We call this whole process the \alert{simulation}, and steps 3-4 a \alert{run} of the simulation.
    \end{frame}

    \begin{frame}{Example 1: Coin flipping}
      Suppose we flip a coin 10 times. What will the distribution of the number of heads look like?

      \pause

      \begin{itemize}[<+->]
        \item Let's define the random variable $H$ to be the number of heads.
        \item We assume that the probability of heads or tails is equal for each flip, and that each flip is independent.
      \end{itemize}
    \end{frame}

    \begin{frame}[fragile]{Random sampling in R}
      The \texttt{sample} function in R lets us randomly select from among several alternatives with equal probability. (We used this last week when we tested for ESP!)

      \bigskip

      To sample from the set $\{0,1\}$ 10 times, with replacement:

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlkwd{sample}\hlstd{(}\hlkwd{c}\hlstd{(}\hlnum{0}\hlstd{,} \hlnum{1}\hlstd{),} \hlnum{10}\hlstd{,} \hlkwc{replace}\hlstd{=T)}
\end{alltt}
\begin{verbatim}
 [1] 0 0 0 1 1 0 0 0 1 1
\end{verbatim}
\end{kframe}
\end{knitrout}
    \end{frame}

    \begin{frame}[fragile]{Replicating a run over and over}
      Every time we execute this run, we'll get a different answer. What we want to know is how often we'll get each answer---e.g., how often do we get 5 versus 6 versus 7?

      \bigskip\pause

      The \texttt{replicate} command lets us run a block of code repeatedly. Inside the code block, we run the \texttt{return} function to tell R what the quantity of interest is. For example, let's run our coin flipping run 15 times:

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlkwd{replicate}\hlstd{(}\hlnum{15}\hlstd{, \{}
  \hlstd{flips} \hlkwb{<-} \hlkwd{sample}\hlstd{(}\hlkwd{c}\hlstd{(}\hlnum{0}\hlstd{,} \hlnum{1}\hlstd{),} \hlnum{10}\hlstd{,} \hlkwc{replace}\hlstd{=T)}
  \hlkwd{return}\hlstd{(}\hlkwd{sum}\hlstd{(flips))}
\hlstd{\})}
\end{alltt}
\begin{verbatim}
 [1] 6 3 5 6 4 5 4 3 6 8 2 4 6 8 6
\end{verbatim}
\end{kframe}
\end{knitrout}
    \end{frame}

    \begin{frame}[fragile]{Replicating a run over and over}
      Why limit ourselves to 15 times? How about 100 times?
      \pause

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlkwd{replicate}\hlstd{(}\hlnum{100}\hlstd{, \{}
  \hlstd{flips} \hlkwb{<-} \hlkwd{sample}\hlstd{(}\hlkwd{c}\hlstd{(}\hlnum{0}\hlstd{,} \hlnum{1}\hlstd{),} \hlnum{10}\hlstd{,} \hlkwc{replace}\hlstd{=T)}
  \hlkwd{return}\hlstd{(}\hlkwd{sum}\hlstd{(flips))}
\hlstd{\})}
\end{alltt}
\begin{verbatim}
  [1] 3 1 6 4 7 6 6 8 6 7 5 5 5 6 7 1 6 5 6 5 5 4 3 2
 [25] 6 6 8 7 6 2 6 6 8 3 6 7 6 5 8 1 5 3 4 3 8 6 7 5
 [49] 3 5 4 6 3 4 5 5 6 5 3 5 6 5 6 4 5 7 4 3 5 4 8 6
 [73] 5 5 2 6 4 6 6 6 4 4 6 6 4 8 4 7 7 4 5 8 6 2 2 4
 [97] 7 5 7 5
\end{verbatim}
\end{kframe}
\end{knitrout}
    \end{frame}

    \begin{frame}{Examining the results of a simulation}
      Since computers are so fast, we'll often do a very large number of runs (e.g., 100,000 times) to even out the idiosyncrasies of any individual run due to randomness.

      \bigskip\pause

      But then we'll have a list of 100,000 numbers representing the result of 100,000 different runs, so we need a way of summarizing those results. To do this, we can look at a histogram of the results, or examine a summary statistic.
    \end{frame}

    \begin{frame}[fragile]
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlstd{results} \hlkwb{<-} \hlkwd{replicate}\hlstd{(}\hlnum{100000}\hlstd{, \{}
  \hlstd{flips} \hlkwb{<-} \hlkwd{sample}\hlstd{(}\hlkwd{c}\hlstd{(}\hlnum{0}\hlstd{,} \hlnum{1}\hlstd{),} \hlnum{10}\hlstd{,} \hlkwc{replace}\hlstd{=T)}
  \hlkwd{sum}\hlstd{(flips)}
\hlstd{\})}
\hlkwd{hist}\hlstd{(results,} \hlkwc{breaks}\hlstd{=}\hlnum{10}\hlstd{,} \hlkwc{col}\hlstd{=}\hlstr{'orange'}\hlstd{)}
\end{alltt}
\end{kframe}
\input{/tmp/figures/unnamed-chunk-6-1.tex}

\end{knitrout}
    \end{frame}

    \begin{frame}[fragile]
      Theory tells us that $H$, the outcome of flipping a fair coin 10 times and counting heads should follow a Binomial distribution with
      \[
        E(H) = np=10\cdot 0.5=5
      \]
      and
      \[
        \text{SD}(H) = \sqrt{np(1-p)}=\sqrt{10\cdot 0.5\cdot 0.5} \approx 1.58.
      \]

      \bigskip\pause

      Let's compare our simulated results against the theoretical results:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlkwd{mean}\hlstd{(results)}
\end{alltt}
\begin{verbatim}
[1] 5.00079
\end{verbatim}
\begin{alltt}
\hlkwd{sd}\hlstd{(results)}
\end{alltt}
\begin{verbatim}
[1] 1.585098
\end{verbatim}
\end{kframe}
\end{knitrout}
    \end{frame}

    \begin{frame}[fragile]{Simulating random variables}
      We have seen how the \texttt{sample} command can be used to draw from a set of alternatives with equal probability (e.g., flipping a coin).

      The \texttt{rnorm} command can be used to draw randomly from a normal distribution. Let's create 10 random heights, with mean 68 (inches) and SD 4.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlkwd{rnorm}\hlstd{(}\hlnum{10}\hlstd{,} \hlnum{68}\hlstd{,} \hlnum{4}\hlstd{)}
\end{alltt}
\begin{verbatim}
 [1] 61.75752 74.42290 67.61342 66.50313 69.74625
 [6] 67.66187 70.59517 70.58163 65.89903 66.39669
\end{verbatim}
\end{kframe}
\end{knitrout}
    \end{frame}

    \begin{frame}
      Let's check that \texttt{rnorm} works as advertised!

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlkwd{hist}\hlstd{(}\hlkwd{rnorm}\hlstd{(}\hlnum{1000}\hlstd{),} \hlkwc{col}\hlstd{=}\hlstr{"orange"}\hlstd{)}
\end{alltt}
\end{kframe}
\input{/tmp/figures/unnamed-chunk-9-1.tex}

\end{knitrout}
    \end{frame}

    \begin{frame}{Example 2: Will I get an A?}
      \begin{itemize}[<+->]
        \item Let's say I'm taking a class with two midterms (each 25\% weight in final grade) and a final exam (50\% weight in final grade).
        \item I just got my score on the first midterm (75\%).
        \item I want to know how likely it is that I can get 90\% or above on my final grade.
        \item This is hard!
      \end{itemize}
    \end{frame}

    \begin{frame}{Example 2: Will I get an A?}
      Let's start by making some assumptions:
      \begin{itemize}[<+->]
        \item I think I can improve on the second midterm, and then even more on the final.
        \item I'll model my Midterm 2 grade as a normal distribution.
        \item My best guess is that I'll get an 80\% on Midterm 2, and I'm 95\% sure it will be between 70\% and 90\%.
        \item So my Midterm 2 grade should be simulated as a normal distribution with mean 80 and SD 5 (since 95\% of a normal distribution is roughly $\pm 2$ SD from the mean).
        \item I think I can improve more on the final; my best guess is that I'll get a 90\%, and I'm 95\% sure I'll get between 80\% and 100\%.
      \end{itemize}
    \end{frame}

    \begin{frame}{Example 2: Will I get an A?}
      \begin{itemize}[<+->]
        \item For each run, we will:
          \begin{enumerate}[<+->]
            \item Randomly draw a Midterm 2 score from its normal distribution, and a Final Exam score from its normal distribution.
            \item Calculate a final score for the course, and see if it's over 90\%.
          \end{enumerate}
        \item Then we will count the percentage of runs where we got 90\%+ for the course. That will be our estimate of the probability of getting an A.
      \end{itemize}
    \end{frame}

    \begin{frame}[fragile]
      \fontsm
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlstd{grades} \hlkwb{<-} \hlkwd{replicate}\hlstd{(}\hlnum{100000}\hlstd{, \{}
  \hlstd{midterm1} \hlkwb{<-} \hlnum{75}
  \hlstd{midterm2} \hlkwb{<-} \hlkwd{rnorm}\hlstd{(}\hlnum{1}\hlstd{,} \hlkwc{mean}\hlstd{=}\hlnum{80}\hlstd{,} \hlkwc{sd}\hlstd{=}\hlnum{5}\hlstd{)}
  \hlstd{final.exam} \hlkwb{<-} \hlkwd{rnorm}\hlstd{(}\hlnum{1}\hlstd{,} \hlkwc{mean}\hlstd{=}\hlnum{90}\hlstd{,} \hlkwc{sd}\hlstd{=}\hlnum{5}\hlstd{)}
  \hlkwd{return}\hlstd{(}\hlnum{.25}\hlopt{*}\hlstd{midterm1} \hlopt{+} \hlnum{0.25}\hlopt{*}\hlstd{midterm2} \hlopt{+} \hlnum{0.5}\hlopt{*}\hlstd{final.exam)}
\hlstd{\})}
\hlkwd{hist}\hlstd{(grades,} \hlkwc{col}\hlstd{=}\hlstr{"orange"}\hlstd{)}
\end{alltt}
\end{kframe}
\input{/tmp/figures/unnamed-chunk-10-1.tex}

\end{knitrout}
    \end{frame}

    \begin{frame}[fragile]
      \fontsm
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlstd{runs} \hlkwb{<-} \hlkwd{replicate}\hlstd{(}\hlnum{100000}\hlstd{, \{}
  \hlstd{midterm1} \hlkwb{<-} \hlnum{75}
  \hlstd{midterm2} \hlkwb{<-} \hlkwd{rnorm}\hlstd{(}\hlnum{1}\hlstd{,} \hlkwc{mean}\hlstd{=}\hlnum{80}\hlstd{,} \hlkwc{sd}\hlstd{=}\hlnum{5}\hlstd{)}
  \hlstd{final.exam} \hlkwb{<-} \hlkwd{rnorm}\hlstd{(}\hlnum{1}\hlstd{,} \hlkwc{mean}\hlstd{=}\hlnum{90}\hlstd{,} \hlkwc{sd}\hlstd{=}\hlnum{5}\hlstd{)}
  \hlkwd{return}\hlstd{(}\hlnum{0.25}\hlopt{*}\hlstd{midterm1} \hlopt{+} \hlnum{0.25}\hlopt{*}\hlstd{midterm2} \hlopt{+} \hlnum{0.5}\hlopt{*}\hlstd{final.exam} \hlopt{>=} \hlnum{90}\hlstd{)}
\hlstd{\})}
\hlkwd{sum}\hlstd{(runs)} \hlopt{/} \hlnum{100000}
\end{alltt}
\begin{verbatim}
[1] 0.01286
\end{verbatim}
\end{kframe}
\end{knitrout}

      \pause
      There's only about a 1.29\% chance that I'll get an A.
    \end{frame}

    \begin{frame}{What if our assumptions are wrong?}
      \begin{itemize}[<+->]
        \item The problem with simulations is that the results can be very sensitive to our assumptions.
        \item To the extent that our assumptions are incorrect, we can't trust the results of the simulation. (``Garbage in, garbage out'')
        \item But the great thing about simulations is that it's easy to change the assumptions and see what effect it has on the results.
        \item For example, what if Midterm 2 is drawn from a normal distribution with mean 90, instead of mean 80?
      \end{itemize}
    \end{frame}

    \begin{frame}[fragile]
      \fontsm
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.137, 0.137, 0.137}\begin{kframe}
\begin{alltt}
\hlstd{runs} \hlkwb{<-} \hlkwd{replicate}\hlstd{(}\hlnum{100000}\hlstd{, \{}
  \hlstd{midterm1} \hlkwb{<-} \hlnum{75}
  \hlstd{midterm2} \hlkwb{<-} \hlkwd{rnorm}\hlstd{(}\hlnum{1}\hlstd{,} \hlkwc{mean}\hlstd{=}\hlnum{90}\hlstd{,} \hlkwc{sd}\hlstd{=}\hlnum{5}\hlstd{)}
  \hlstd{final.exam} \hlkwb{<-} \hlkwd{rnorm}\hlstd{(}\hlnum{1}\hlstd{,} \hlkwc{mean}\hlstd{=}\hlnum{90}\hlstd{,} \hlkwc{sd}\hlstd{=}\hlnum{5}\hlstd{)}
  \hlkwd{return}\hlstd{(}\hlnum{0.25}\hlopt{*}\hlstd{midterm1} \hlopt{+} \hlnum{0.25}\hlopt{*}\hlstd{midterm2} \hlopt{+} \hlnum{0.5}\hlopt{*}\hlstd{final.exam} \hlopt{>=} \hlnum{90}\hlstd{)}
\hlstd{\})}
\hlkwd{sum}\hlstd{(runs)} \hlopt{/} \hlnum{100000}
\end{alltt}
\begin{verbatim}
[1] 0.0881
\end{verbatim}
\end{kframe}
\end{knitrout}

      \pause
      Under this new assumption, there's an 8.81\% chance that I'll get an A.
    \end{frame}
  \end{darkframes}
\end{document}
